### ISSUE TITLE
Add scale information to plots

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy#242]
when plotting spatial information, scale information is. We should discuss if we can add this to our plots if scale information is available. E.g. in `sq.pl.co_occurrence`, mark distance with actual units. 

It might be more appropriate to raise this issue at scanpy actually, because it mainly concerns `sc.pl.spatial`, but discussing here might not hurt.

**Comment by giovp** [comment]
@hspitzer do you have code for doing this easily? I think it would make sense to import in squidpy the `sc.pl.spatial` function from scanpy, and allow for this addition as well as plotting across multiple slides as discussed in #332

**Comment by giovp** [comment]
it's coming real fast with #437
