### ISSUE TITLE
Deployment finish

### ISSUE THREAD

**Issue by michalk8** [theislab/squidpy#269]
### Type of the feature

- [ ] New function in `sqduipy.im`?
- [ ] New function in `squidpy.gr`?
- [ ] New function in `squidpy.pl`?
- [ ] Change an existing functionality, such as default behavior?
- [x] Other?

### Description

TODOs from #266 
- [x] optional (add explanation to FeatureMixin.features_segmentation)
- [x] update README/index.rst with figure
- [x] update links to pre-print
- [x] bump CI time from 10 minutes (3.8 on Mac seems slow-ish)
- [x] change `LICENSE` (also in `setup.py`, the license keywords and the classifier, see [here](https://pypi.org/classifiers/))

**Comment by giovp** [comment]
one more thing to remember is to chnage license to bsd3 clause. I'll do it tomo

**Comment by hspitzer** [comment]
@michalk8 I'm slowly working through my mentions of the last days. You guys did great work already. Please let me know if I'm missing any questions:
- `squidpy._io`: can be removed
- add explanation to featureMixin.features_segmentation: will do!
