### ISSUE TITLE
notes on docu

### ISSUE THREAD

**Issue by SabrinaRichter** [theislab/squidpy#271]
fancy to see that what started during the hackathon is now grown up and has it's own readthedocs 😊 
noticed some minor stuff when randomly looking through it, maybe interesting, if not resolved by any of you earlier, I will try to fix them tomorrow morning

- If you wish to contribute to Squidpy, please make sure you’re familiar with our Contributing guide.
-> We are happy about any contributions! Before you start, check out our Contribution guide here.

- are all the images squidpy works with called microscopy images? also IMC and so on? replace by 'tissue images'? also makes the whole thing clearer

- https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_imc.html plots and legends overlap

- there is something wrong in the 'Ligand-receptor interaction analysis'  in the Analyze Visium H&E data tutorial

**Comment by giovp** [comment]
remember to re-clone the repo for any changes! and thank you in advance!

**Comment by hspitzer** [comment]
re the images: I'm struggling with this as well. I called them sometimes microscopy images and sometime tissue images. I think for the IMC data we never use the raw images, but their preprocessed count x gene matrices, right? But we could of course use a few selected channels as images to extract morphological features... 
I'd go for calling them "tissue images", this is more general.
