### ISSUE TITLE
troubleshooting section in contributing.rst

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy#272]
### Type of the feature

- [ ] New function in `sqduipy.im`?
- [ ] New function in `squidpy.gr`?
- [ ] New function in `squidpy.pl`?
- [ ] Change an existing functionality, such as default behavior?
- [ ] Other?

### Description

There used to be a troubleshooting section in the contributing guideline like this:
```
Troubleshooting
 ---------------
 - **shellcheck: command not found**
   This happens during the linting step and is most likely due to missing ``shellcheck`` on the system.
   See these `installation instructions <https://github.com/koalaman/shellcheck#installing>`__ on how to install it.
```

Is there a specific reason it was deleted? It might be good to collect these issues somewhere - in addition to `shellcheck` I just ran into another one with `pyenchant` which gave me an error similar to "The enchant C library was not found"

**Comment by michalk8** [comment]
> Is there a specific reason it was deleted? It might be good to collect these issues somewhere - in addition to shellcheck I just ran into another one with pyenchant which gave me an error similar to "The enchant C library was not found"

Shellcheck has been removed from the pre-commit and since it was the only thing there, I've removed the whole section.
As for `pyenchant`, I think this happens when building docs, we should add link to https://pyenchant.github.io/pyenchant/install.html

**Comment by hspitzer** [comment]
> > Is there a specific reason it was deleted? It might be good to collect these issues somewhere - in addition to shellcheck I just ran into another one with pyenchant which gave me an error similar to "The enchant C library was not found"
> 
> Shellcheck has been removed from the pre-commit and since it was the only thing there, I've removed the whole section.

ah ok, makes sense. 

> As for `pyenchant`, I think this happens when building docs, we should add link to https://pyenchant.github.io/pyenchant/install.html

Yes, I had to install enchant using `brew`. That would be a nice hint to have, but tbh the error message is also quite clear. So if that's the only error that occurs, I'm also happy to leave it out of the contributing guide.
