### ISSUE TITLE
issue with mypy

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy#274]
### Description

On current master, `mypy` throws errors for me but not for @giovp 
I have:
- cloned squidpy
- installed pre-commit `pre-commit clean; pre-commit install`
- changed docstring of a file
- done `git commit` which results in the error

Is there an issue with my environment?

### Minimal reproducible example

```python
...
```

### Traceback

<details>

```pytb
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

squidpy/gr/_utils.py:86:16: error: Item "ndarray" of "Union[ndarray, Any]" has no attribute "tocsc"  [union-attr]
squidpy/gr/_ppatterns.py:284: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ppatterns.py:285: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ppatterns.py:286: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ppatterns.py:287: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ppatterns.py:288: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:662: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:663: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:708:17: error: Incompatible types in assignment (expression has type "ndarray", variable has type "List[ndarray]")  [assignment]
squidpy/gr/_ligrec.py:710:31: error: Subclass of "List[ndarray]" and "ndarray" cannot exist: would have incompatible method signatures  [unreachable]
squidpy/gr/_ligrec.py:712:9: error: Statement is unreachable  [unreachable]
squidpy/gr/_ligrec.py:746: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:747: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:748: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:749: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:750: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:751: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:752: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:817:21: error: Incompatible types in assignment (expression has type "None", variable has type "ndarray")  [assignment]
squidpy/gr/_build.py:186:5: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/gr/_build.py:186:12: error: Item "ndarray" of "Union[Any, ndarray]" has no attribute "multiply"  [union-attr]
squidpy/pl/_utils.py:205:15: error: Item "ndarray" of "Union[Any, ndarray]" has no attribute "A"  [union-attr]
squidpy/pl/_utils.py:212:5: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/pl/_utils.py:239:19: error: Item "ndarray" of "Union[Any, ndarray]" has no attribute "toarray"  [union-attr]
squidpy/pl/_utils.py:562: error: Function "numpy.array" is not valid as a type  [valid-type]
squidpy/pl/_utils.py:562: note: Perhaps you need "Callable[...]" or a callback protocol?
squidpy/pl/_utils.py:572:28: error: np.array? has no attribute "T"  [attr-defined]
squidpy/im/_utils.py:17:5: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/im/_feature_mixin.py:342:13: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/im/_feature_mixin.py:370:56: error: Incompatible types in assignment (expression has type "ndarray", target has type "int")  [assignment]
squidpy/im/_feature_mixin.py:374:56: error: Incompatible types in assignment (expression has type "number[Any]", target has type "int")  [assignment]
squidpy/im/_feature_mixin.py:375:55: error: Incompatible types in assignment (expression has type "number[Any]", target has type "int")  [assignment]
squidpy/im/_feature_mixin.py:387:63: error: Incompatible types in assignment (expression has type "number[Any]", target has type "int")  [assignment]
squidpy/im/_feature_mixin.py:388:62: error: Incompatible types in assignment (expression has type "number[Any]", target has type "int")  [assignment]
squidpy/im/_container.py:833:19: error: Incompatible types in assignment (expression has type "ImageContainer", variable has type "ndarray")  [assignment]
squidpy/im/_container.py:834:13: error: "memoryview" has no attribute "attrs"  [attr-defined]
squidpy/im/_container.py:836:20: error: Incompatible return value type (got "ndarray", expected "Optional[ImageContainer]")  [return-value]
squidpy/im/_container.py:836: error: unused 'type: ignore' comment
squidpy/im/_segment.py:146:9: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/im/_segment.py:166:9: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/pl/_interactive/_controller.py:192:9: error: Returning Any from function declared to return "ndarray"  [no-any-return]
Found 40 errors in 10 files (checked 1 source file)
```

</details>

### Version

...

**Comment by michalk8** [comment]
I have mypy version `0.790` (`mypy --version`) and have tested `0.8`, running `pre-commit run --all-files` works.
I am using Python 3.8.5. The errors of type:
```bash
squidpy/gr/_ppatterns.py:284: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
```
come from `data-science-types`, but we use `from __future__ import annotations` at the top, so there should be no problem.
I'd try a creatinga fresh new env.

**Comment by hspitzer** [comment]
> I have mypy version `0.790` (`mypy --version`) and have tested `0.8`, running `pre-commit run --all-files` works.
> I am using Python 3.8.5. The errors of type:
> 
> ```shell
> squidpy/gr/_ppatterns.py:284: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
> ```
> 
> come from `data-science-types`, but we use `from __future__ import annotations` at the top, so there should be no problem.
> I'd try a creatinga fresh new env.

With fresh env you mean a new python virtualenv / conda where I install squidpy in? I've already deleted `.tox` several times and re-installed squidpy. Will try with a new environment.

**Comment by michalk8** [comment]
> With fresh env you mean a new python virtualenv / conda where I install squidpy in? I've already deleted .tox several times and re-installed squidpy. Will try with a new environment.

Yes, new python env.

> Just noticed that I don't have mypy installed - I thought that this would be installed with tox?

No this is handled by pre-commit. You could also try cleaning the cache (mine is located in `~/.cache/pre-commit/`).

**Comment by hspitzer** [comment]
Hm, still no luck. With a completely new Conda (with python 3.8), and only squidpy installed (`pip install -e'.[dev,test]'`), I get the same error

<details>
> tox -e lint
lint create: /Users/hannah.spitzer/projects/spatial_scanpy/squidpy/.tox/lint
lint installdeps: pre-commit>=2.9.3
lint installed: appdirs==1.4.4,cfgv==3.2.0,distlib==0.3.1,filelock==3.0.12,identify==1.5.13,nodeenv==1.5.0,pre-commit==2.10.1,PyYAML==5.4.1,six==1.15.0,toml==0.10.2,virtualenv==20.4.2
lint run-test-pre: PYTHONHASHSEED='610168850'
lint run-test: commands[0] | pre-commit run --all-files --show-diff-on-failure
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy:numpy>=1.15.0,pandas,scipy>=1.5.0.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/psf/black:toml.
[INFO] Initializing environment for https://github.com/timothycrosley/isort.
[INFO] Initializing environment for https://github.com/timothycrosley/isort:toml.
[INFO] Initializing environment for https://github.com/asottile/yesqa.
[INFO] Initializing environment for https://github.com/asottile/yesqa:flake8-blind-except,flake8-bugbear,flake8-builtins,flake8-comprehensions,flake8-docstrings,flake8-logging-format,flake8-mock,flake8-pytest-style,flake8-rst-docstrings,flake8-string-format,flake8-tidy-imports.
[INFO] Initializing environment for https://github.com/macisamuele/language-formatters-pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/myint/autoflake.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8:flake8-blind-except,flake8-bugbear,flake8-builtins,flake8-comprehensions,flake8-docstrings,flake8-logging-format,flake8-mock,flake8-pytest-style,flake8-rst-docstrings,flake8-string-format,flake8-tidy-imports.
[INFO] Initializing environment for https://github.com/jumanjihouse/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/myint/rstcheck.
[INFO] Initializing environment for https://github.com/asottile/blacken-docs.
[INFO] Initializing environment for https://github.com/asottile/blacken-docs:black==20.8b1.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/pre-commit/pygrep-hooks.
[INFO] Initializing environment for https://github.com/PyCQA/doc8.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/timothycrosley/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/yesqa.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/macisamuele/language-formatters-pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/myint/autoflake.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/myint/rstcheck.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/blacken-docs.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/doc8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

squidpy/gr/_utils.py:86:16: error: Item "ndarray" of "Union[ndarray, Any]" has no attribute "tocsc"  [union-attr]
squidpy/pl/_utils.py:205:15: error: Item "ndarray" of "Union[Any, ndarray]" has no attribute "A"  [union-attr]
squidpy/pl/_utils.py:212:5: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/pl/_utils.py:239:19: error: Item "ndarray" of "Union[Any, ndarray]" has no attribute "toarray"  [union-attr]
squidpy/pl/_utils.py:562: error: Function "numpy.array" is not valid as a type  [valid-type]
squidpy/pl/_utils.py:562: note: Perhaps you need "Callable[...]" or a callback protocol?
squidpy/pl/_utils.py:572:28: error: np.array? has no attribute "T"  [attr-defined]
squidpy/gr/_ppatterns.py:284: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ppatterns.py:285: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ppatterns.py:286: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ppatterns.py:287: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ppatterns.py:288: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_build.py:186:5: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/gr/_build.py:186:12: error: Item "ndarray" of "Union[Any, ndarray]" has no attribute "multiply"  [union-attr]
squidpy/gr/_ligrec.py:662: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:663: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:708:17: error: Incompatible types in assignment (expression has type "ndarray", variable has type "List[ndarray]")  [assignment]
squidpy/gr/_ligrec.py:710:31: error: Subclass of "List[ndarray]" and "ndarray" cannot exist: would have incompatible method signatures  [unreachable]
squidpy/gr/_ligrec.py:712:9: error: Statement is unreachable  [unreachable]
squidpy/gr/_ligrec.py:746: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:747: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:748: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:749: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:750: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:751: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:752: error: "ndarray" expects no type arguments, but 1 given  [type-arg]
squidpy/gr/_ligrec.py:817:21: error: Incompatible types in assignment (expression has type "None", variable has type "ndarray")  [assignment]
squidpy/im/_utils.py:17:5: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/im/_feature_mixin.py:342:13: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/im/_feature_mixin.py:370:56: error: Incompatible types in assignment (expression has type "ndarray", target has type "int")  [assignment]
squidpy/im/_feature_mixin.py:374:56: error: Incompatible types in assignment (expression has type "number[Any]", target has type "int")  [assignment]
squidpy/im/_feature_mixin.py:375:55: error: Incompatible types in assignment (expression has type "number[Any]", target has type "int")  [assignment]
squidpy/im/_feature_mixin.py:387:63: error: Incompatible types in assignment (expression has type "number[Any]", target has type "int")  [assignment]
squidpy/im/_feature_mixin.py:388:62: error: Incompatible types in assignment (expression has type "number[Any]", target has type "int")  [assignment]
squidpy/im/_container.py:833:19: error: Incompatible types in assignment (expression has type "ImageContainer", variable has type "ndarray")  [assignment]
squidpy/im/_container.py:834:13: error: "memoryview" has no attribute "attrs"  [attr-defined]
squidpy/im/_container.py:836: error: unused 'type: ignore' comment
squidpy/im/_container.py:836:20: error: Incompatible return value type (got "ndarray", expected "Optional[ImageContainer]")  [return-value]
squidpy/im/_segment.py:146:9: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/im/_segment.py:166:9: error: Returning Any from function declared to return "ndarray"  [no-any-return]
squidpy/pl/_interactive/_controller.py:192:9: error: Returning Any from function declared to return "ndarray"  [no-any-return]
Found 40 errors in 10 files (checked 58 source files)

black....................................................................Passed
isort....................................................................Passed
Strip unnecessary `# noqa`s..............................................Passed
Pretty format YAML.......................................................Passed
Detect Private Key.......................................................Passed
Check for merge conflicts................................................Passed
Check python ast.........................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check for added large files..............................................Passed
Check that executables have shebangs.....................................Passed
Fix python encoding pragma...............................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Tests should end in _test.py.............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check Yaml...............................................................Passed
Check Toml...............................................................Passed
Fix requirements.txt.....................................................Passed
autoflake................................................................Passed
flake8...................................................................Passed
Check executable files use .sh extension.................................Passed
rstcheck.................................................................Passed
blacken-docs.............................................................Passed
pyupgrade................................................................Passed
check for eval().........................................................Passed
type annotations not comments............................................Passed
check blanket noqa.......................................................Passed
rst ``code`` is two backticks............................................Passed
rst directives end with two colons.......................................Passed
rst ``inline code`` next to normal text..................................Passed
doc8.....................................................................Passed
ERROR: InvocationError for command /Users/hannah.spitzer/projects/spatial_scanpy/squidpy/.tox/lint/bin/pre-commit run --all-files --show-diff-on-failure (exited with code 1)
</details>

**Comment by michalk8** [comment]
Ok, can confirm this happens on my PC as well (after removing pre-commit cache), not sure why though.

**Comment by michalk8** [comment]
@hspitzer let me know if #276 fixed it for you (it should)

**Comment by hspitzer** [comment]
thanks, works perfectly now!
