### ISSUE TITLE
Support deletion of single layers in Image Container

### ISSUE THREAD

**Issue by MxMstrmn** [theislab/squidpy#285]
### Type of the feature

- [x] New function in `sqduipy.im`?
- [ ] New function in `squidpy.gr`?
- [ ] New function in `squidpy.pl`?
- [ ] Change an existing functionality, such as default behavior?
- [ ] Other?

### Description
Support deletion of images from image container like 
``` del img['image']```

**Comment by giovp** [comment]
hi @MxMstrmn ,

thanks for trying out squidpy!
could you elaborate on a use case where that would be useful? 

thank you!

**Comment by MxMstrmn** [comment]
Sure, basically I modify parts of my image and do not need the original image anymore: 
```
img = sq.im.ImageContainer(
    img=dataset_folder + "/" + f"{dataset_name}_image.tif",
    layer="original",
    lazy=True,
    channel_dim="channels_4",
)

img.add_img(
    img["original"].data[..., :3], channel_dim="channels_3", layer="image", lazy=True
)
```
Deletion would allow me to circumvent passing the layer argument every time as my image container only contains the default "image" layer.
