### ISSUE TITLE
Fix `Edit on GitHub` for generated files

### ISSUE THREAD

**Issue by michalk8** [theislab/squidpy#295]
### Description

See https://github.com/theislab/squidpy/pull/294#issuecomment-785309863

### Minimal reproducible example

```python
...
```

### Traceback

<details>

```pytb
...
```

</details>

### Version

...

**Comment by giovp** [comment]
can we close this @michalk8 ?

**Comment by michalk8** [comment]
Yes, let's close this, should be fine since we have the `[souce]` in the docs. Alternative would be to do it as in `scanpy`/`scvelo`,
but that's already what the `[source]` does or we can just remove the `Edit on GitHub` in the future.
