### ISSUE TITLE
Numba issue

### ISSUE THREAD

**Issue by franciscogrisanti** [theislab/squidpy#297]
Hi guys! Thanks for this great tool. 

I'm having some issues trying to run the basic tutorials. I managed to install squidpy in a conda env, with your environment.yml shared in the HE Notebook tutorial

I'm running everything in a 

`Linux-4.15.0-128-generic-x86_64-with-glibc2.27`

...

###  Trying this 

```python
sq.gr.ligrec(
    adata,
    n_perms=10,
    cluster_key="cluster",
)

```

### Results in this

UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (LOAD_ASSERTION_ERROR) found

File "/data/u/franciscog/rich_ST/analysis", line 80:
<source missing, REPL/exec in use?>

```

**Comment by michalk8** [comment]
Hi @franciscogrisanti ,

For Python3.9, I've found this [issue](https://github.com/numba/numba/issues/6614#issuecomment-754803293) and this [one](https://github.com/numba/numba/issues/6739), both related to the above error.
In short, once `numba>=0.53.0` is out, it should work also on Python3.9. Currently, release candidate for `0.53.0` can be installed using [these](https://numba.discourse.group/t/helping-test-numba-0-53-0-rc/519) instructions).
For completeness, I'm using Python3.8.5 and numba `0.52.0` and there haven't had any issues.

@giovp maybe we should have 3.9 on the CI as well soon.

**Comment by franciscogrisanti** [comment]
Yes @michalk8 that did it. 

@giovp Maybe it would be nice for now to change environment.yml to

```python
name: squidpy
channels:
-   conda-forge
dependencies:
-   python=3.8
-   pip
-   pip:
    -   squidpy>=1.0.0
    -   esda>=2.3.1
    -   libpysal>=4.3.0
    -   astropy>=4.1
    -   numba==0.52.0
```

**Comment by giovp** [comment]
@franciscogrisanti that's great!
I was about to raise the same point. I think it makes sense @michalk8 , what do you think?

**Comment by michalk8** [comment]
Great that it now works! I've update the environment in https://github.com/theislab/squidpy_notebooks/commit/6debd50409e7be0e8963f0ba46b53aa74e5c8da4 and will create the issue for the CI shortly. Closing this.
