### ISSUE TITLE
Return EI_sim in Moran's I

### ISSUE THREAD

**Issue by Hrovatin** [theislab/squidpy#307]
Also return EI_sim in Moran's I computation (currently it seems that only mi.I, mi.p_z_sim, mi.VI_sim are returned). This is needed to determine how many stds away from mean is the I.

**Comment by giovp** [comment]
btw @Hrovatin we bow have moran's implemented in scanpy, you can just clone the latest master and do
```python
import scanpy as sc
sc.metrics.morans_i(adata)
```
and the return is the same as gearys' C

**Comment by Hrovatin** [comment]
Thanks, I did not realise that this PR was finished.
