### ISSUE TITLE
read_visium() referenced in docs

### ISSUE THREAD

**Issue by kevinyamauchi** [theislab/squidpy#319]
### Description
First off, thanks for making a great tool with tons of examples/tutorials! I noticed that `scapy.read_visium()` is referenced in the ["Import spatial data in AnnData and Squidpy" tutorial](https://user-images.githubusercontent.com/1120672/116033849-7c754c80-a662-11eb-9b44-df8dfed3d47a.png) and it appears to have been removed in https://github.com/theislab/squidpy/pull/273. If it is helpful, I am happy to make a small PR to remove the reference.

### Minimal reproducible example
Screenshot from https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

<img width="1507" alt="Screenshot 2021-04-26 at 07 46 54" src="https://user-images.githubusercontent.com/1120672/116034470-9b281300-a663-11eb-857e-8192d5fe4a61.png">

### Version
"latest" docs accessed on April 26, 2021

**Comment by michalk8** [comment]
Hi @kevinyamauchi 
in #273 `squidpy.read_visium_data` was removed in favor of [scanpy.read_visium](https://scanpy.readthedocs.io/en/stable/api/scanpy.read_visium.html#scanpy.read_visium), since the former was used only during development and wrapped the latter (and constructed the ImageContainer).

**Comment by kevinyamauchi** [comment]
Thanks for the quick response and explanation, @michalk8 !

**Comment by michalk8** [comment]
I believe this can be closed then, feel free to reopen.
