### ISSUE TITLE
Allow channel=None in sq.im.segment

### ISSUE THREAD

**Issue by AnnaChristina** [theislab/squidpy#328]
### Type of the feature

- [x] New function in `sqduipy.im`?
- [ ] New function in `squidpy.gr`?
- [ ] New function in `squidpy.pl`?
- [x] Change an existing functionality, such as default behavior?
- [ ] Other?

### Description

...

currently working on external segmentation methods that run on multiple channels.
https://squidpy.readthedocs.io/en/latest/api/squidpy.im.segment.html#squidpy.im.segment

could we allow `channel=None` which then runs the segmentation on multiple channels instead just one?

e.g. stardist has an H&E model that runs on 3 channels which would be nice to add as custom model

**Comment by giovp** [comment]
@michalk8 I think this should be relatively straightforward to change behaviour right? can be worked in #324 ?

**Comment by michalk8** [comment]
> @michalk8 I think this should be relatively straightforward to change behaviour right? can be worked in #324 ?

Yes, will just need to remove some extra checks, not a problem.

**Comment by michalk8** [comment]
closed via #324

**Comment by AnnaChristina** [comment]
is this closed yet? I still see the default as `channel: int=0` in `sq.im.segment`?

**Comment by giovp** [comment]
> is this closed yet? I still see the default as `channel: int=0` in `sq.im.segment`?

this was merged into `dev` , not `master`, does that work?

**Comment by AnnaChristina** [comment]
ah sorry yes. will install dev and check if this works then in the notebook. thanks!
