### ISSUE TITLE
Subset data for Squidpy

### ISSUE THREAD

**Issue by ccruizm** [theislab/squidpy#339]
Good day,

I am trying to subset an anndata object with ST information to be used in Squidpy. However, I am not sure how to subset the same coordinates used in the ImageCOntainer object used on Squidpy and the anndata object generated by Scanpy. Do you have any insights on how to do this, please? 

Thanks in advance!

**Comment by giovp** [comment]
Hi @ccruizm ,

thank you for the interest in squidpy! I moved it in the appropriate repo for clarification.

I'd suggest you to have a look at this tutorial: https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

in general, coordinates saved in `adata.obsm["spatial"]` represents the coordinates in the source microscopy image (depending on the tech at hand). You can then put scaling factors like this:

```python
spatial_key = "spatial"
library_id = "tissue42"
adata.uns[spatial_key] = {library_id: {}}
adata.uns[spatial_key][library_id]["images"] = {}
adata.uns[spatial_key][library_id]["images"] = {"hires": image}
adata.uns[spatial_key][library_id]["scalefactors"] = {"tissue_hires_scalef": 1, "spot_diameter_fullres": 0.5}
```

if you then want to visualize hires images (which are still much much lower res than the source), you can pass the key of the image to `sc.pl.spatial(..., img_key="hires")` to select the appropriate one.

Does this help? if no, can you provide a more precise example/question on what's the task you are trying to accomplish?

**Comment by giovp** [comment]
@ccruizm can you provide feedback on the issue? if resolved, feel free to close it. Thank you!

**Comment by ccruizm** [comment]
Sorry I did not reply to this. Actually, I used the approach mentioned in https://github.com/theislab/squidpy/issues/337 and works nicely! 

I used 
```
adata = ...
img = sq.im.ImageContainer(...)
adata_subset = img.crop_corner(0, 0, (1000, 1000)).subset(adata)
```

And I could successfully subset the AnnData object and crop the image :)

Thanks for the help and looking forward to the next updates!
