### ISSUE TITLE
Provide info on layers as attribute in ImageContainer

### ISSUE THREAD

**Issue by MxMstrmn** [theislab/squidpy#342]
### Type of the feature

- [x] New function in `sqduipy.im`?
- [ ] New function in `squidpy.gr`?
- [ ] New function in `squidpy.pl`?
- [ ] Change an existing functionality, such as default behavior?
- [ ] Other?

### Description
Maybe some missunderstanding on my side, but it would be nice to provide the `layers` info as attribute: 
Currently, I am getting this info via: `list(img.data.keys())`
<img src=https://user-images.githubusercontent.com/24990533/118489785-85b37f80-b71d-11eb-827b-babfd4d9cc50.png width=340>

**Comment by giovp** [comment]
it's an interesting feature, is it doable to add in #329 @hspitzer if not supported?

**Comment by hspitzer** [comment]
Yes, this is certainly doable! I'd prefer to do this in a separate PR, the z-stacks one is already shaping up to be another monster PR. Adding sth like `img.layers` or `img.layer_names` does not interfere at all with the z-stacks changes.

**Comment by michalk8** [comment]
@MxMstrmn `list(img)` should return you the layer.

**Comment by hspitzer** [comment]
Closing this, as you can do `list(img)` to get the layer names. I'll also document that in the updated ImageContainer tutorial.
