### ISSUE TITLE
add overview page for class methods

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy#344]
### Type of the feature

- [ ] New function in `sqduipy.im`?
- [ ] New function in `squidpy.gr`?
- [ ] New function in `squidpy.pl`?
- [ ] Change an existing functionality, such as default behavior?
- [x] Other?

### Description

we'll add a couple of examples for `ImageContainer` methods. For this, I was wondering 
- if it is possible to add the examples to the `ImageContainer` docs (like we add links to examples for the API functions)
- if we can create an overview page for all class methods. E.g. something like the table that we have in the API atm, where you see the function (class method) and a short description. You can then click on these to go to the method docs (can be on the same page). Or, alternatively we could at least have an entry in the navigation bar on the left for each class method. I played around with sphinx a bit, and think this:
```
.. autosummary::
    :toctree: stubs
    :recursive:
    
    ImageContainer
```
does something very similar to what I'm after. 
![image](https://user-images.githubusercontent.com/13350159/118671875-1f4f5f80-b7f8-11eb-8b27-a73089db2273.png)

this also seems to add the gallery links - at least to the overview page, which would also be fine.

**Comment by michalk8** [comment]
closed via #356 (however, it will be improve before the release [`Classes` section])
