### ISSUE TITLE
New release 1.1.0

### ISSUE THREAD

**Issue by michalk8** [theislab/squidpy#366]
### Type of the feature

- [ ] New function in `sqduipy.im`?
- [ ] New function in `squidpy.gr`?
- [ ] New function in `squidpy.pl`?
- [ ] Change an existing functionality, such as default behavior?
- [x] Other?

### Description

This issue is used to track `1.1.0` release and what needs to be done/merged before. TODOs:
- [x] make sure deployment works again (credentials problem)*
- [x] fix README on PyPI (`tox -e readme`)
- [x] verify that regeneration works both for master and dev*
- [ ] close issues that have been dealt with

\* should be working (in theory), if not, it's not an issue to fix after release

**Comment by hspitzer** [comment]
additional todos:
- [ ] fix classes API for Image Container on docs (currently included twice, once under API, and once under Classes)
- [ ] add 2 missing examples in docs (ImageContainer: image crop generation and apply function) @hspitzer

**Comment by michalk8** [comment]
closed via https://github.com/theislab/squidpy/commit/e9c8802ce1bce6e60225c5345c339cebb2458dee
