### ISSUE TITLE
Orientation of interaction matrix

### ISSUE THREAD

**Issue by AnnaChristina** [theislab/squidpy#371]
I recently used the interaction matirx to analyze connections in several datasets. 

It seems that 'self' cell types are columns and neighbouring cell types are rows correct? wouln't is be more intuitive to read this the other way around? because ideally I would like to now which neighbours one cell type has, it shows the same information but would just be easier to read.

**Comment by giovp** [comment]
hi @AnnaChristina , sorry for late reply on this. I am not sure I understand why this would be more intuitive, the way it's computed resemble the first iteration we had with `attribute_matrix` from netowkrx. https://networkx.org/documentation/stable/reference/generated/networkx.linalg.attrmatrix.attr_matrix.html

I think this also makes sense for allowing normalized_rows argument.
