### ISSUE TITLE
 cylindrical shell option for sq.gr.spatial_neighbors

### ISSUE THREAD

**Issue by AnnaChristina** [theislab/squidpy#388]
### Type of the feature

- [ ] New function in `sqduipy.im`?
- [x] New function in `squidpy.gr`?
- [ ] New function in `squidpy.pl`?
- [ ] Change an existing functionality, such as default behavior?
- [ ] Other?

### Description

Additional feature request für `sq.gr.spatial_neighbors` to allow a cylindrical shell as neighbourhood option, so all cells are considered as neighbors for min_radius < x < max_radius. This would be beneficial for ncem, see https://github.com/theislab/ncem/issues/22 

As ncem's backend is based on squidpy, I would like to add this.

This would include the following changes: rename `radius` to `max_radius` and add `min_radius` with default 0. I can create a PR for this.

**Comment by michalk8** [comment]
closed via #393
