### ISSUE TITLE
how to add spatial transcriptomics to the h5ad file

### ISSUE THREAD

**Issue by FADHLyemen** [theislab/squidpy#391]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...

Hi, 
If we have scrna-seq file and other spatial image, how to use scanpy to visualize them both
I found visum example but I am interested in combining 10x scrna-seq and other image such as slideseq, mFISH?
https://scanpy-tutorials.readthedocs.io/en/latest/spatial/basic-analysis.html

**Comment by giovp** [comment]
hello @FADHLyemen was the suggested tutorial useful?
