### ISSUE TITLE
Filter output from sq.gr.ligrec

### ISSUE THREAD

**Issue by ccruizm** [theislab/squidpy#394]
Good day!

I would like to know if it is possible to filter the final interactions from `sq.gr.ligrec` using information stored in the 'metadata' dataframe. For instance, select only L-R pairs where `plasma_membrane_peripheral_intercell_source == True` and `plasma_membrane_peripheral_intercell_target==True`.

Thanks in advance!

**Comment by michalk8** [comment]
Hi @ccruizm ,
the following snippet should do the trick:
```python
md = res['metadata']
index = md.loc[md['plasma_membrane_peripheral_intercell_target']].index
res_new = {"means": res["means"].loc[index],
           "pvalues": res["pvalues"].loc[index],
           "metadata": md.loc[index]}
```

**Comment by ccruizm** [comment]
Thanks @michalk8! works nicely
