### ISSUE TITLE
How can I use Squidpy 1.1.1 with numpy

### ISSUE THREAD

**Issue by ziqlu0722** [theislab/squidpy#408]
...Hi! I'm trying to import the newest Squidpy, while I have some problems with the environment. I found when I have numpy <=1.20, I got the below error: 

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/_utils.py in <module>
     46 try:
---> 47     from numpy.typing import NDArray
     48 except ImportError:

ImportError: cannot import name 'NDArray' from 'numpy.typing' (/Users/luz21/miniconda3/envs/new_tg/lib/python3.8/site-packages/numpy/typing/__init__.py)

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-79a991327b07> in <module>
----> 1 import squidpy
      2 squidpy.__version__

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/__init__.py in <module>
      9 
     10 from squidpy import datasets
---> 11 import squidpy.gr
     12 import squidpy.im
     13 import squidpy.pl

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/gr/__init__.py in <module>
      1 """The graph module."""
----> 2 from squidpy.gr._build import spatial_neighbors
      3 from squidpy.gr._nhood import nhood_enrichment, centrality_scores, interaction_matrix
      4 from squidpy.gr._sepal import sepal
      5 from squidpy.gr._ligrec import ligrec

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/gr/_build.py in <module>
     18 
     19 from squidpy._docs import d, inject_docs
---> 20 from squidpy._utils import NDArrayA
     21 from squidpy.gr._utils import _save_data, _assert_positive, _assert_spatial_basis
     22 from squidpy._constants._constants import CoordType, Transform

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/_utils.py in <module>
     48 except ImportError:
     49     ScalarType = TypeVar("ScalarType", bound=np.generic, covariant=True)
---> 50     NDArray = np.ndarray[Any, np.dtype[ScalarType]]  # type: ignore[misc]
     51 NDArrayA = NDArray[Any]
     52 

TypeError: 'numpy._DTypeMeta' object is not subscriptable`

But when I have numpy==1.21.1, I got the error below:
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-79a991327b07> in <module>
----> 1 import squidpy
      2 squidpy.__version__

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/__init__.py in <module>
      8 __version__ = "1.1.1"
      9 
---> 10 from squidpy import datasets
     11 import squidpy.gr
     12 import squidpy.im

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/datasets/__init__.py in <module>
----> 1 from squidpy.datasets._image import *  # noqa: F403
      2 from squidpy.datasets._dataset import *  # noqa: F403

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/datasets/_image.py in <module>
      1 from copy import copy
      2 
----> 3 from squidpy.datasets._utils import ImgMetadata
      4 
      5 _vfic = ImgMetadata(

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/squidpy/datasets/_utils.py in <module>
      6 import os
      7 
----> 8 from scanpy import read, logging as logg
      9 from anndata import AnnData
     10 from scanpy._utils import check_presence_download

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/scanpy/__init__.py in <module>
      4 
      5 if not within_flit():  # see function docstring on why this is there
----> 6     from ._utils import check_versions
      7 
      8     check_versions()

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/scanpy/_utils/__init__.py in <module>
     27 from .. import logging as logg
     28 
---> 29 from .compute.is_constant import is_constant
     30 
     31 

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/scanpy/_utils/compute/is_constant.py in <module>
      3 
      4 import numpy as np
----> 5 from numba import njit
      6 from scipy import sparse
      7 

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/numba/__init__.py in <module>
    196 
    197 _ensure_llvm()
--> 198 _ensure_critical_deps()
    199 
    200 # we know llvmlite is working as the above tests passed, import it now as SVML

~/miniconda3/envs/new_tg/lib/python3.8/site-packages/numba/__init__.py in _ensure_critical_deps()
    136         raise ImportError("Numba needs NumPy 1.17 or greater")
    137     elif numpy_version > (1, 20):
--> 138         raise ImportError("Numba needs NumPy 1.20 or less")
    139 
    140     try:

ImportError: Numba needs NumPy 1.20 or less`

Could you please help with right numpy version here? Thank you!

**Comment by michalk8** [comment]
Hi @ziqlu0722 , thanks for noticing this, should be fixed on `dev` by c10a8ef.
Can you try as `pip install git+https://github.com/theislab/squidpy@dev`?

**Comment by ziqlu0722** [comment]
Hi @michalk8 , thank you for the prompt help! Will this be fixed for the official release?

**Comment by ilan-gold** [comment]
+1 experiencing this.  Using the dev branch worked though.
