### ISSUE TITLE
Do the spatial analysis in squidpy have to be done on a sample by sample basis?

### ISSUE THREAD

**Issue by shanzaayub** [theislab/squidpy#417]
Hi there! I was wondering if the spatial analysis in squipy, e.g. `sq.gr.co_occurence(...)` have to be done on a sample by sample basis? I'm asking in the case where let's say I have an AnnData object with data from multiple different samples, then do I have to break up the AnnData by sample and then apply squipy's algorithms or is squidpy able to run it's algorithm on all the samples simultaneously? Thanks!

**Comment by giovp** [comment]
Hi @shanzaayub , sorry for late reply. Yeah as of now you'd have to perform it on a sample by sample basis. For graph-based metrics you could also use the trick explained in this comment https://github.com/theislab/squidpy/issues/318#issuecomment-886541340

we will eventually implement ways to compute scores considering batching but don't have an estimate of such feature

**Comment by shanzaayub** [comment]
Ah okay, thank you!
