### ISSUE TITLE
Plotting values on top of segmentation mask

### ISSUE THREAD

**Issue by ivirshup** [theislab/squidpy#427]
## Description

From a few discussions with @AnnaChristina, @hspitzer, and @giovp it sounds like being able to color cell segments with values of the cells is a commonly desired feature.

I've made a very quick proof on concept [here](https://github.com/ivirshup/notebooks/blob/master/segmentation_masks/01_plot_segmentation.ipynb) which mostly deals with mapping the values correctly. Definitely still needs to be wrapped up with some nicer tooling and arguments, but it gets the data structures and a plotted image. Examples:

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/8238804/139063218-bf3fffba-de5a-429f-969e-a5e9d04621cb.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/8238804/139063283-1728626c-6186-4822-928f-385b1eb62380.png">

**Comment by giovp** [comment]
this is so cool, quick question: I see you are using `datashader`, I assume it's the best tool for the job. How does it behave with matplotlib? e.g. can we assign it to an axis and keep same logic for labels, colorbar etc ? thanks!

**Comment by giovp** [comment]
I think I know what you mean when you mentioned the "failing resize" of matplotlib @ivirshup . The boundaries fails:
![image](https://user-images.githubusercontent.com/25887487/151708179-fa2a640c-cb2d-4836-87dc-d7d313bd302d.png)

if I rescale with skimage (0.5), issue is still there:
![image](https://user-images.githubusercontent.com/25887487/151708193-11845db5-8753-483d-a577-b8a04708d269.png)

**Comment by giovp** [comment]
ok been experimenting with matplotlib integration of datashader and must say...not great:


<details>
<summary>Details</summary>

```python
fig, ax = plt.subplots(1, figsize=(5, 5))
dsshow(
    coords,
    ds.Point("x", "y"),
    ds.count_cat("value_to_plot"),
    color_key=col_map,
    shade_hook=tf.dynspread,  # , threshold=0.50, how="over"),
    ax=ax,
    aspect="equal",
)
# ax.invert_yaxis()
plt.legend(handles=artist4.get_legend_elements())
plt.title("Point category")
```
![image](https://user-images.githubusercontent.com/25887487/151710641-c3aeb6ad-215f-4908-b724-cb2aec735091.png)


</details>

the rendering is not as good as the other one. 

with `shade_hook=tf.spread` it removes the weird white lines, but the size of the masks is also increased and looks wrong. Played around with tf.dynspread args and if image small enough then they go away

<details>
<summary>Details</summary>

```python
fig, ax = plt.subplots(1, figsize=(3, 3), dpi=150)
dsshow(
    coords,
    ds.Point("x", "y"),
    ds.count_cat("value_to_plot"),
    color_key=col_map,
    shade_hook=partial(
        tf.dynspread,
        threshold=0.99,
        max_px=10,
    ),  # px=2, how="over", shape="square"),
    ax=ax,
    aspect="equal",
)
dsshow(
    coords_bounds,
    ds.Point("x", "y"),
    ds.count_cat("value_to_plot"),
    color_key=["black"],
    ax=ax,
    aspect="equal",
)

# ax.invert_yaxis()
plt.legend(handles=artist4.get_legend_elements())
plt.title("Point category")

```

![image](https://user-images.githubusercontent.com/25887487/151711659-18dc9fce-0dfe-4a5c-86c1-f36599c89fae.png)

</details>

**Comment by ivirshup** [comment]
Oh, the way I wrote that it's going to strongly assume the output canvas has pixels matching to the point coordinates. For that I was thinking you'd basically totally generate the image with `datashader`, then `plt.imshow` it.

I think I finally figured out how to do this with just existing dependencies though. Mapping the values of a numpy array (like `pd.Series.map({...})`) is weirdly difficult! Of course I found the `skimage` function that's way faster after I got something working.

This one rescales quite nicely with the image size.

```python
res = np.empty(seg_p16.values.shape, dtype=seg_p16.values.dtype)
skimage.util.map_array(
    seg_p16.values,
    adata_p16.obs["cell_id"].values,
    adata_p16.obs["Cluster"].cat.codes.values + 1,
    res,
)

with plt.rc_context({"figure.figsize": (5, 5), "figure.dpi": 150}):
    plt.imshow(
        skimage.color.label2rgb(
            res,
            colors=mpl.colors.to_rgba_array(adata.uns["Cluster_colors"]),
            bg_label=0,
            bg_color=(1, 1, 1, 0),
            image_alpha=0,
        )
    )
```

<img width="566" alt="image" src="https://user-images.githubusercontent.com/8238804/151890251-59bf00b8-73ec-4e12-ba92-ebb5829e2b0a.png">

And with boundaries (with ugly code):

```python
with plt.rc_context({"figure.figsize": (5, 5), "figure.dpi": 200}):
    plt.imshow(
        skimage.color.label2rgb(
            res,
            colors=mpl.colors.to_rgba_array(adata.uns["Cluster_colors"]),
            bg_label=0,
            bg_color=(1, 1, 1, 0),
        ) - skimage.segmentation.find_boundaries(res)[:, :, None]
    )
```

<img width="765" alt="image" src="https://user-images.githubusercontent.com/8238804/151891799-c708c595-34cc-4ebb-8fb6-60ec8f90ee71.png">

**Comment by ivirshup** [comment]
Plotting just boundaries with a color:

```python
from skimage.morphology import erosion, square

n_pixels = 7
"""Number of pixels for the border"""

res = np.empty(seg_p16.values.shape, dtype=seg_p16.values.dtype)
skimage.util.map_array(
    seg_p16.values,
    adata_p16.obs["cell_id"].values,
    adata_p16.obs["Cluster"].cat.codes.values + 1,
    res,
)
res[res == erosion(res, square(n_pixels))] = 0

with plt.rc_context({"figure.figsize": (5, 5), "figure.dpi": 200}):
    plt.imshow(
        skimage.color.label2rgb(
            res,
            colors=mpl.colors.to_rgba_array(adata.uns["Cluster_colors"]),
            bg_label=0,
            bg_color=(1, 1, 1, 0),
        )
    )
```

<img width="556" alt="image" src="https://user-images.githubusercontent.com/8238804/153061811-ca350b82-bb49-4672-a065-8c532e882a44.png">


For if you want to see the image underneath, e.g. to highlight some cells.

**Comment by giovp** [comment]
with latest push on #437 you can do something like this:

<details>
<summary>example</summary>

```python
from squidpy.pl._spatial import spatial_segment
adata = sq.datasets.mibitof()
spatial_segment(
    adata,
    color=["Cluster", "cell_size"],
    groups=["Fibroblast", "Endothelial"],
    na_color=(0, 0, 0, 0),
    library_key="library_id",
    cell_id_key="cell_id",
    img=True,
    seg=True,
    seg_transparent=True,
    seg_boundaries=True,
    seg_erosionpx=15,
    figsize=(5, 5),
    cmap="magma",
    vmin=500,
)
```

![image](https://user-images.githubusercontent.com/25887487/154117055-73916eb6-6659-4d58-8632-4a0f2bc30ae8.png)

</details>

you can take a look at the function here: https://github.com/theislab/squidpy/blob/0a831c5fc3ea4c1de5925a555c85d0868ef57fc8/squidpy/pl/_spatial_utils.py#L567

must say it's ugly to add transparency properly, using `label2rgb` out of the box as you do doesnt' work. Meant to ask you, can you check shape of `res` from your example? I'd be surprised if it's `(H,W,4)` .
Thanks for all the pointers, I thinkw e are getting closer

**Comment by ivirshup** [comment]
I think `res` should be 2d since it's a segmentation mask.

It looks like skimage ([issue](https://github.com/scikit-image/scikit-image/issues/4091), [PR adding to docs](https://github.com/scikit-image/scikit-image/pull/4527)) recommends you do something like:

```python
plt.imshow(
    skimage.color.label2rgb(
        res,
        colors=mpl.colors.to_rgba_array(adata.uns["Cluster_colors"]),
        bg_label=0,
        image=image_to_overlay_on,
    )
)
```

But I'm having some trouble getting the image to plot.

**Comment by giovp** [comment]
exactly but if so still the output should be a rgba array for proper transparency with the underlying image. Also, for RGB color images they are grayscaled first: https://scikit-image.org/docs/dev/api/skimage.color.html#label2rgb

I think the approach proposed keepsthe  RGB of underlying image as well as RGBA of segmentation mask (colored by discrete or continuos values) , so to get consistency across different color strategies (e.g. transparency of out-groups annotations) but agree it's ugly

**Comment by ivirshup** [comment]
Ah, I think I see what you mean now. You'd like the output of `label2rgb` to have an `alpha` channel, right?

I think you could do this yourself, with something like:

```python
color_array = np.vstack(
    [
        np.zeros((1, 4)),
        mpl.colors.to_rgba_array(adata.uns["Cluster_colors"]),
    ]
)
seg_as_categories = np.empty(seg_p16.values.shape, dtype=seg_p16.values.dtype)

skimage.util.map_array(
    seg_p16.values,
    adata_p16.obs["cell_id"].values,
    adata_p16.obs["Cluster"].cat.codes.values + 1,
    seg_as_categories,
)
seg_as_rgba = color_array[seg_as_categories]
```

Where `seg_as_rgba` is a `(px_x, px_y, 4)` array, `seg_as_categories` is a `(px_x, px_y)` array.

Looking at the plots above, I think having a grayscale background image does make a lot of sense. It's a bit hard to see the difference between the segments and the underlying image. Could also give the segmentation mask itself a border? Getting a bit meta here.

**Comment by giovp** [comment]
thanks a lot for the feedback, I tried out and it works but then I have problems with stuff downstream. E.g. seg erosion. I understand it's less efficient since I need to call map_array essentially twice (one for map_array and one for label2rgb) but I couldn't find another way to do it without it. Using only one call to map_array would work for continuous values but then the figure would look different whether categorical or continuous values are plotted.

> Looking at the plots above, I think having a grayscale background image does make a lot of sense.

this can be already done independly on the _map_seg call but on the _img call (where grayscaling, single channel and cmap can be used)

> Could also give the segmentation mask itself a border? Getting a bit meta here.

this is also already done. it's also in the example but since the background is also black difficult to see. But if no image is plotted, then clearly visible.

**Comment by ivirshup** [comment]
> it's less efficient since I need to call map_array essentially twice

I don't think I'd worry too much about this. When I did some `%time` benchmarking in a notebook, it looked like `map_array` took a negligible amount of the runtime compared to actually generating the plot with`matplotlib`.

Plus now that everything is grouped, it should be easier to fiddle with specifics of handling later.

> this is also already done. it's also in the example but since the background is also black difficult to see. But if no image is plotted, then clearly visible.

Ah, I had initially thought that `seg_boundaries` was the "mode" (e.g. to plot boundaries of the segmentation masks, not the whole thing), and `seg_erosionpx` set the width of that boundary.

I think it would make sense to be able to set the color and width of the boundary.
