### ISSUE TITLE
4i dataset

### ISSUE THREAD

**Issue by yuanzhiyuan** [theislab/squidpy#431]
...

Hi, a subset of 4i dataset is available in https://squidpy.readthedocs.io/en/stable/api/squidpy.datasets.four_i.html#squidpy.datasets.four_i.
I am wondering how to load/find the rest part of the 4i data reported in original science paper?

**Comment by hspitzer** [comment]
Hi @yuanzhiyuan 
We received this subset of the 4i dataset directly from the authors of the original science paper. Unfortunately I am not aware of any public location of the entire dataset. I'd suggest to contact the authors directly for full access to this dataset.

As a side note: if you are interested in how we processed the data to the ImageContainer format, you can have a look at this preprocessing notebook here: https://github.com/theislab/squidpy_reproducibility/blob/master/notebooks/prepare_data/4i.ipynb

**Comment by giovp** [comment]
@yuanzhiyuan hope this solves your issue, I'll close this but feel free to re-open in case not addressed.
