### ISSUE TITLE
How to convert 10X Spatial Gene Expression Dataset 1.3 to squidpy.datasets

### ISSUE THREAD

**Issue by JunMa11** [theislab/squidpy#439]
Hi all,

Thanks for sharing this great tool. I'm a newcomer to SRT and this tool is very very helpful to me.

I'd like to convert the latest 10X Spatial Gene Expression Dataset to `squidpy.datasets`, for example, the [breast cancer data](https://www.10xgenomics.com/resources/datasets/human-breast-cancer-ductal-carcinoma-in-situ-invasive-carcinoma-ffpe-1-standard-1-3-0).

However, I do not find tutorials about how the existing squidpy.datasets were obtained, e.g., [squidpy.datasets.visium_hne_adata](https://squidpy.readthedocs.io/en/stable/api/squidpy.datasets.visium_hne_adata.html#squidpy.datasets.visium_hne_adata).

Would it be possible for you to share a tutorial about how to convert this [visium dataset](https://www.10xgenomics.com/resources/datasets/human-breast-cancer-ductal-carcinoma-in-situ-invasive-carcinoma-ffpe-1-standard-1-3-0) to `squidpy.datasets`?

![1641331504(1)](https://user-images.githubusercontent.com/19947331/148125874-f2d09f8b-b952-4743-a8eb-eb507c3d3846.png)

Best regards,
Jun

**Comment by giovp** [comment]
Hi @JunMa11 ,

thanks for the interest in squidpy. So it's very easy, there is a reading function in scanpy for now (we'll soon move it to Squidpy) here: https://scanpy.readthedocs.io/en/stable/generated/scanpy.read_visium.html

you can just input the path of that folder and the scanpy function takes care of loading everything needed in the right place.  

the `squidpy.datasets` are a set of pre-processed datasets for tutorial purposes so not really useful for users. 

If you want to download that dataset in particular, you might also be able to use this function (which will also be ported to squidpy soon): https://scanpy.readthedocs.io/en/stable/generated/scanpy.datasets.visium_sge.html#scanpy.datasets.visium_sge

if it's not available there, then you'd have to manually download it and read with with `scanpy.read_visium`. When that function will be ported in Squidpy it'll be easy to add new datasets as well as new techs (not only visium).

Let me know if it works!
Giovanni
