### ISSUE TITLE
Reading module for visium and other techs

### ISSUE THREAD

**Issue by giovp** [theislab/squidpy#441]
## Description

reading module for reading visium and other techs
https://scanpy.readthedocs.io/en/stable/generated/scanpy.read_visium.html

**Comment by giovp** [comment]
questions from @gokceneraslan on scanpy slack:

- remove hardcoded `read_h5` from `read_visium` and account for other formats for counts.
- find a way to reconstruct spatial coordinates from missing info based solely on barcode information.

**Comment by giovp** [comment]
@gokceneraslan reporting for the read visium function that @dineshpalli is working on, from previous conv in slack you mentioned this file:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4565826

which we could read with this [ad.read_mtx](https://anndata.readthedocs.io/en/stable/anndata.read_mtx.html) . Maybe also useful to have [ad.read_text](https://anndata.readthedocs.io/en/stable/anndata.read_text.html) just in case. Any other format  that comes to mind?

**Comment by michalk8** [comment]
closed via #468
