### ISSUE TITLE
argument of type 'NoneType' is not iterable error when running ligand receptor analysis 

### ISSUE THREAD

**Issue by rachel662** [theislab/squidpy#443]
## Description

argument of type 'NoneType' is not iterable error when running ligand receptor analysis 

## Minimal reproducible example

```python
res = sq.gr.ligrec(
    adata,
    n_perms=1000,
    cluster_key="celltype_mapped_refined",
    copy=True,
    use_raw=False,
    transmitter_params={"categories": "ligand"},
    receiver_params={"categories": "receptor"},
)
```

<details>

```pytb

## Traceback
<!-- If applicable, replace `...` with an error traceback below: -->

TypeError                                 Traceback (most recent call last)
<ipython-input-42-58bec6b89f26> in <module>
----> 1 res = sq.gr.ligrec(
      2     adata,
      3     n_perms=1000,
      4     cluster_key="celltype_mapped_refined",
      5     copy=True,

~\anaconda3\envs\IMC\lib\site-packages\squidpy\gr\_ligrec.py in ligrec(adata, cluster_key, interactions, complex_policy, threshold, corr_method, corr_axis, use_raw, copy, key_added, gene_symbols, **kwargs)
    642     with _genesymbols(adata, key=gene_symbols, use_raw=use_raw, make_unique=False):
    643         return (  # type: ignore[no-any-return]
--> 644             PermutationTest(adata, use_raw=use_raw)
    645             .prepare(interactions, complex_policy=complex_policy, **kwargs)
    646             .test(

~\anaconda3\envs\IMC\lib\site-packages\squidpy\gr\_ligrec.py in prepare(self, interactions, complex_policy, interactions_params, transmitter_params, receiver_params, **_)
    606             interactions[TARGET] = interactions[TARGET].str.replace("^COMPLEX:", "", regex=True)
    607 
--> 608         _ = super().prepare(interactions, complex_policy=complex_policy)
    609         return self
    610 

~\anaconda3\envs\IMC\lib\site-packages\squidpy\gr\_ligrec.py in prepare(self, interactions, complex_policy)
    287             logg.warning(f"Removed `{n_genes_prior - self._data.shape[1]}` duplicate gene(s)")
    288 
--> 289         self._filter_interactions_complexes(complex_policy)
    290         self._filter_interactions_by_genes()
    291         self._trim_data()

~\anaconda3\envs\IMC\lib\site-packages\squidpy\gr\_ligrec.py in _filter_interactions_complexes(self, complex_policy)
    509         if complex_policy == ComplexPolicy.MIN:
    510             logg.debug("DEBUG: Selecting genes from complexes based on minimum average expression")
--> 511             self.interactions[SOURCE] = self.interactions[SOURCE].apply(find_min_gene_in_complex)
    512             self.interactions[TARGET] = self.interactions[TARGET].apply(find_min_gene_in_complex)
    513         elif complex_policy == ComplexPolicy.ALL:

~\anaconda3\envs\IMC\lib\site-packages\pandas\core\series.py in apply(self, func, convert_dtype, args, **kwargs)
   4355         dtype: float64
   4356         """
-> 4357         return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
   4358 
   4359     def _reduce(

~\anaconda3\envs\IMC\lib\site-packages\pandas\core\apply.py in apply(self)
   1041             return self.apply_str()
   1042 
-> 1043         return self.apply_standard()
   1044 
   1045     def agg(self):

~\anaconda3\envs\IMC\lib\site-packages\pandas\core\apply.py in apply_standard(self)
   1096                 # List[Union[Callable[..., Any], str]]]]]"; expected
   1097                 # "Callable[[Any], Any]"
-> 1098                 mapped = lib.map_infer(
   1099                     values,
   1100                     f,  # type: ignore[arg-type]

~\anaconda3\envs\IMC\lib\site-packages\pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()

~\anaconda3\envs\IMC\lib\site-packages\squidpy\gr\_ligrec.py in find_min_gene_in_complex(_complex)
    491 
    492         def find_min_gene_in_complex(_complex: str) -> str | None:
--> 493             if "_" not in _complex:
    494                 return _complex
    495             complexes = [c for c in _complex.split("_") if c in self._data.columns]

```

</details>

## Version
 1.1.2

**Comment by michalk8** [comment]
Hi @rachel662 ,

this was reported in https://github.com/theislab/squidpy/issues/433 and should've been fixed https://github.com/theislab/squidpy/pull/434, it's on `dev` . Can try installing it as `pip install git+https://github.com/theislab/squidpy@dev` and lmk if it works?

**Comment by rachel662** [comment]
thanks so much, I will let you know, I'm working in a conda environment do you think this might impact other modules in the environment at all?

**Comment by michalk8** [comment]
Don't think so, we've only introduced 1 extra requirement on `dev` (numba>=0.52.0) since the last release was made.

**Comment by michalk8** [comment]
I think this can be closed, if the bug is still present on `dev`, please re-open.

**Comment by rgranit** [comment]
@michalk8 I've encountered the same issue and based on the instructions here install the Dev version

```shell
conda list | grep squid
squidpy                   1.1.3.dev19+g075a09b          pypi_0    pypi
```

Yet when I load squidpy in Jupyter (after restarting the kernel etc) it still claims that it's iv V1.1.2 and the issue remains

```python 
print(f"squidpy=={sq.__version__}")
```
An I doing something wrong when loading squidpy? any suggestions?

Thanks!

**Comment by michalk8** [comment]
@rgranit 
Can confirm that using the instructions I've provided, I can get the version you've specified.
Seems like it install an older version of dev, `conda list | grep squid` gave me before:
`squidpy                   1.1.3.dev34+gf7c7eb3           dev_0    <develop>`

**Comment by michalk8** [comment]
>  Can confirm that using the instructions I've provided, I can get the version you've specified.

Seems just like it's a different version number coming from `conda`, but the files are the same as the ones latest `dev` commit, so it shouldn't happen.
@rgranit Would you mind running this piece of code here: https://github.com/theislab/squidpy/issues/433#issuecomment-1037492625 with your `AnnData` object? This roughly follows the `squidpy.gr.ligrec` and should not raise the above error.

**Comment by rgranit** [comment]
@michalk8 Thanks. I ran the code you've referred me to and unfortunately encountered the same error.. what I don't understand is why jupyter says that I've running `squidpy==1.1.2` while conda lists `1.1.3.dev19+g075a09b` ? should I do something special to import the dev version?

**Comment by giovp** [comment]
could i tbe that you have conflicting versions in base and your ocnda env? are you sure the conda env is active when running the notebook?

**Comment by rgranit** [comment]
@michalk8 @giovp it seems that the dev version is installed and that the dev [__init.py__](https://github.com/theislab/squidpy/blob/dev/squidpy/__init__.py) file still mentions v.1.12 ...

In any case I still do not have a solution to this 'NoneType', any suggestions? 

Thanks 🙏

**Comment by michalk8** [comment]
> @michalk8 @giovp it seems that the dev version is installed and that the dev [init.py](https://github.com/theislab/squidpy/blob/dev/squidpy/__init__.py) file still mentions v.1.12 ...

This is to be expected, unfortunately. I will add a PR to add `squidpy.__full_version__` to also include the current commit hash.

@rgranit This branch should fix it: https://github.com/theislab/squidpy/tree/fix/ligrec-none
I'm a bit hesitant to merge it since I don' really understand why the previous fix doesn't work, but will merge once I know this finally fixes it. Would you mind testing this, since I cannot reproduce? Would also try installing `squidpy` as follows, if possible:
```bash
git clone https://github.com/theislab/squidpy/
cd squidpy
git checkout fix/ligrec-none
pip install -e.
```

**Comment by rgranit** [comment]
Thanks @michalk8 @giovp - the fix work! appreciate the help

**Comment by michalk8** [comment]
> Thanks @michalk8 @giovp - the fix work! appreciate the help

Thank you for testing it so quickly, I will merge this to ``dev`` asap.
