### ISSUE TITLE
How should data be preprocessed for ligrec

### ISSUE THREAD

**Issue by grst** [theislab/squidpy#446]
What format does `gr.ligrec` expect the gene expression to be in, i.e. raw UMI counts/normalized/log-normalized/...?
Sorry if I missed it in the docs!

**Comment by giovp** [comment]
Normalized! Also best to log-transform them. CellphoneDB originally has option for non log-transformed data and transforms them in the function call. We don't do that, just taking anndata.X (or layers).

**Comment by grst** [comment]
:ok_hand:

Thanks for the quick response!
