### ISSUE TITLE
KeyError: "Unable to get the spot diameter"

### ISSUE THREAD

**Issue by dst53** [theislab/squidpy#447]
Hello,

I am loading a 10x visium experiment and would like to use the squidpy interactive viewer. However, I am running into an issue with img.interactive(). KeyError: "Unable to get the spot diameter from `adata.uns['spatial']['0']['scalefactors']['spot_diameter_fullres']]`"

This happens even when explicitly setting the library id. I am not sure why squidpy is trying to access ['0'] as the library ID, which does not exist in the anndata object

```
import squidpy as sq
import scanpy as sc
import numpy as np

sc.logging.print_header()

```
scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.21.5 scipy==1.7.3 pandas==1.3.5 scikit-learn==1.0.2 statsmodels==0.13.1 python-igraph==0.9.9 pynndescent==0.5.5
```
print(f"squidpy=={sq.__version__}")
```
squidpy==1.1.2
```
adata = sc.read_visium("outs",
                       count_file='raw_feature_bc_matrix.h5',
                       source_image_path='tissue_hires_image_LM_SD_1216_1.png')
adata
```
AnnData object with n_obs × n_vars = 4992 × 36945
    obs: 'in_tissue', 'array_row', 'array_col'
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'spatial'
    obsm: 'spatial'
```
img = sq.im.ImageContainer(img="tissue_hires_image_LM_SD_1216_1.png")
img
```
ImageContainer[shape=(1922, 2000), layers=['image']]
```
viewer = img.interactive(adata, spatial_key='spatial', library_id='LM_SD_1216_1')
```
KeyError: "Unable to get the spot diameter from `adata.uns['spatial']['0']['scalefactors']['spot_diameter_fullres']]`"
```
adata.uns['spatial']['LM_SD_1216_1']['scalefactors']['spot_diameter_fullres']
```
129.04054855798105

Thank you

**Comment by giovp** [comment]
@dst53 thank you for interest in squidpy, sorry for late reply.
Did you check that in `adata.uns["spatial"]` you have this library id `LM_SD_1216_1 ` ?
If that''s the case, then you need to pass the library_id to the image container as well when you initialize it:

```python
img = sq.im.ImageContainer(img="tissue_hires_image_LM_SD_1216_1.png", library_id="LM_SD_1216_1")
img
```

let me know if it works

**Comment by dst53** [comment]
Hi @giovp 

Yes, this worked! Many thanks.
