### ISSUE TITLE
QC & cell-type annotation steps in tutorial?

### ISSUE THREAD

**Issue by yangjun9095** [theislab/squidpy#452]
Hi all,

First, amazing job on the squidpy package as well as nicely elaborated tutorials! 
I'm currently taking some slide-seq (v2) data, and wonder if I can apply scanpy/squidpy platform earlier on, not just for visualization and quantitative data analysis, but also for Quality Control (QC) and assign cell-types in each clusters. I'm aware that this is very dataset-specific, and hard to be generalized, but wanted to see these steps behind the current tutorial. Could you please unveil this part of the squidpy/scanpy notebooks for processing the data?

p.s. Also, I wonder where I can get the information of how to convert the raw aligned data to h5ad/anndata objects. If there's a tutorial so that I can see the whole workflow from the raw sequencing data all the way to the plots, that'd be fascinating. 

Thanks very much,
Yang-Joon

**Comment by giovp** [comment]
hi @yangjun9095 

thank you for the interest in squidpy. All the repoducibility notebooks from the paper can be found here: https://github.com/theislab/squidpy_reproducibility

most of the pre-0processing/QC uses scanpy functions, some of it can be seenhere: https://scanpy-tutorials.readthedocs.io/en/latest/spatial/basic-analysis.html. (scanpy notebook for legacy reasons).

> p.s. Also, I wonder where I can get the information of how to convert the raw aligned data to h5ad/anndata objects. If there's a tutorial so that I can see the whole workflow from the raw sequencing data all the way to the plots, that'd be fascinating.

for raw-aligned you mean the output of spaceranger? if yes, then you can just use the scanpy function read_visium https://scanpy.readthedocs.io/en/stable/generated/scanpy.read_visium.html  if you mean some other data format, you can take a look at this tutorial on how to read general data into squidpy: https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

HTH

**Comment by yangjun9095** [comment]
Thanks a lot, Giovanni! This is super helpful!

I actually wanted to load the output from slideseq-tools package (https://github.com/MacoskoLab/slideseq-tools/tree/0.1).
I think I can start with the tutorial that you shared. Thanks a lot again!

Best,
Yang-Joon
