### ISSUE TITLE
Method for quickly calculating spatial statistics for multiple images together (different samples from same cohort and replicates)

### ISSUE THREAD

**Issue by johnhickey22** [theislab/squidpy#457]
...I'm hoping do some of the spatial analyses presented in squidpy but across many different multiplexed images (e.g. different donors, sample types, and replicates). All of the examples online were for individual sample analysis. Is there a way to do this type of analysis across multiple images (use as replicates) for a given condition? I know I can load all of my sample data into one adata object, with columns for observations, but the x, y positions of each image will overlap. Loading each into its own adata object seems clunky, especially when I want to start collecting replicate information about spatial statistics. For example if I want to use sq.gr.co_occurrence, I would need to iterate through adata/unique conditions (images) then I may not have the same "cell type" in each image replicate making it hard to concatenate replicates there, since the output is not linked to the "cell type" key but just an nxn numpy array. I'm hoping that there is some simple implementation within squidpy that I am missing and you could point me there to help subset and perform statistics on replicates and subconditions.

**Comment by giovp** [comment]
hi @johnhickey22 ,

thanks for the interest in squidpy, we are very aware of this problem and are working toward making the analysis tools working on such settings. For now you could try simply concatenating anndata objects like this:\https://github.com/theislab/squidpy/issues/318#issuecomment-886541340\

in order to create a block diagonal obsp sparse matrix. The spatial statistics should work out of the box in that settings but again we haven't really tested it so it's something we don't know for sure. We  are hoping to cut a new release in ~a month in which that feature would be included.

**Comment by johnhickey22** [comment]
Fantastic. Thanks so much about sending the workaround. I'll try it out and see how it works with images that do not share all the same clusters. Will look forward to the next release. Thanks for creating such useful tools for the community.

**Comment by johnhickey22** [comment]
Is there a reason why do you not plot the co_occurance probability ratio on a log scale as default since this is a ratio?

**Comment by johnhickey22** [comment]
hi @giovp - Thanks for pointing out the previous workaround. I've tried it for my data but does not look like it is working. I've tried to do another workaround by computing the probabilities individually and then concatenating the probabilities for each cell pair and location after the fact. However, I am running into issues with the interval scales being different between samples. My tissues are of different sizes, would it be possible to instead of putting in the n_steps and determining the interval automatically from _find_min_max function, and just specify the total interested distance (often the biology of interest is smaller scales than the entire image) and then also the step size. This would also allow me to concatenate replicates. 
Another suggestion for plotting the co_occurance probability ratio on a log scale as default since this is a ratio, lower ratios tend to be underrepresented. Thanks for your help!

**Comment by giovp** [comment]
hi @johnhickey22 , with new release out soon we'll add support to build spatial graph across multiple slices. You can then run that function as is since the graph will be built by only considering points in the same slide. You can follow development here #516

**Comment by giovp** [comment]
#516 has been merged, you can now use the co-occurrence score across multiple slides, if you build the graph by setting the `library_key` argument. Let me know if you try it out, will close this but feel free to reopen if not solved.
