### ISSUE TITLE
Changing channel names of layer in ImageContainer

### ISSUE THREAD

**Issue by jwrth** [theislab/squidpy#458]
Is it possible to directly change the name of the channels in a layer of an ImageContainer?

Explanation:
I have the ImageContainer `image` with the layer `'image'` and 4 channels do the following:
```
image['image']['channels'] = list('abcd')
```
Afterwards the names of the channels in the Imagecontainer stay unchanged. 

A workaround that I found is to first extract the DataArray, change the channels there and add it back to the ImageContainer:
```
array = image['image']
array['channels'] = list('abcd')
print(array['channels'].to_numpy())
>>> ['a' 'b' 'c' 'd']

# add it back to the ImageContainer
image.add_img(array, layer='image')

# now the channels in the ImageContainer are changed
```

But is there a direct way to change the channel names?

Thanks a lot in advance!

**Comment by michalk8** [comment]
Hi @jwrth , sorry for such a late reply. This seems to be the default behavior of `xarray`, e.g.:
```python
ds = xr.Dataset()

ds['image'] = xr.DataArray(
    da.from_array(np.random.normal(size=(42, 42, 1, 3))),
    dims=["x", "y", "z", "channels"]
)
ds['image']['channels'] = [1, 2, 3]
ds['image']['channels']  # [0, 1, 2]
```
However, you can set the `channels` name globally for the dataset as `image.data['channels'] = ['a', 'b', 'c', 'd']`

**Comment by jwrth** [comment]
That works! Thanks!
