### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by sailseem** [theislab/squidpy#475]
Dear Developer,

It's a great package, while I am new to this. I have a silly question about the IMC data analysis. What's the exact data input of this # load the pre-processed dataset adata = sq.datasets.imc()?

Is that like a csv file containing the X, Y coordinates, each antibody expression, cell cluster annotation (after run like TSNE), and also the individual tiffs of each channel or OME-tiff? 

Thanks in advance for your valuable time!

**Comment by giovp** [comment]
dear @sailseem thanks for interest in Squidpy!

> What's the exact data input of this # load the pre-processed dataset adata = sq.datasets.imc(

https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

I'd check out this tutorial to understand better to understand which anndata slot to use for your data, let me know if it works

**Comment by sailseem** [comment]
Thanks for your help! Well, i am just wondering when I performed the sq.gr.co_occurrence function.   What if my "adata" have multiple images inside and I wanna do the distance calculation of each image or maybe the mean distance in certain groups. Besides subset the adata, is there any easy way to do this? 
Thanks a lot.

**Comment by giovp** [comment]
hi @sailseem sorry for late reply. Unfortuntaely as of now there is None, you'd have to compute the co-occurrence for each anndata yourself and then aggregate downstream. We plan to support more of these type of workflows but it will take a while. I'll close this for now but please feel free to re-open if not solved.
