### ISSUE TITLE
Dev version for sq.gr.ligrec

### ISSUE THREAD

**Issue by MertDemirdizen** [theislab/squidpy#492]
...
Hi, I have seen that other people encountered the same issue and solved but I could not fix it. Sorry if I am missing something or not writing in a proper format. It is my first time using python and github. 

I want to run sq.gr.ligrec and get TypeError: argument of type 'NoneType' is not iterable as issue #443. 
When I tried to run 
pip install git+https://github.com/theislab/squidpy@dev
I get 
WARNING: Did not find branch or tag 'dev', assuming revision or ref.
  Running command git checkout -q dev
  error: pathspec 'dev' did not match any file(s) known to git
WARNING: Discarding git+https://github.com/theislab/squidpy@dev. Command errored out with exit status 1: git checkout -q dev Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q dev Check the logs for full command output

I tried when squidpy 1.1.2 is installed and not installed. I also tried in an environment but I could not install it. 

I also tried [this](https://github.com/theislab/squidpy/issues/372#issuecomment-867898831), but the git switch dev line gives the error:
fatal: invalid reference: dev

I installed the squidpy by deleting @dev as pip install git+https://github.com/theislab/squidpy@dev but I could not import

**Comment by MertDemirdizen** [comment]
> Hi @MertDemirdizen ,
> 
> we've recently removed the `dev` version, `master` should be used instead as `pip install git+https://github.com/theislab/squidpy@master`. Let me know if this works for you!

Hi,

Thank you for your quick reply and interest. I am getting an error when I try to import it:


File "C:\ProgramData\Anaconda3\lib\site-packages\squidpy\im\_feature_mixin.py", line 10, in <module>
    from skimage.feature import graycoprops, graycomatrix

ImportError: cannot import name 'graycoprops' from 'skimage.feature' (C:\ProgramData\Anaconda3\lib\site-packages\skimage\feature\__init__.py)

**Comment by michalk8** [comment]
>  from skimage.feature import graycoprops, graycomatrix

This is caused because I forgot to bump the `scikit-image` from below (requires now `0.19.0`), should be fixed in https://github.com/theislab/squidpy/commit/1958896df5e0e686701ac7de30884480ed238882. You can try installing it as `"pip install scikit-image>=0.19"` or running `pip install git+https://github.com/theislab/squidpy@master` again.

**Comment by MertDemirdizen** [comment]
> > from skimage.feature import graycoprops, graycomatrix
> 
> This is caused because I forgot to bump the `scikit-image` from below (requires now `0.19.0`), should be fixed in [1958896](https://github.com/theislab/squidpy/commit/1958896df5e0e686701ac7de30884480ed238882). You can try installing it as `pip install "scikit-image>=0.19"` or running `pip install git+https://github.com/theislab/squidpy@master` again.

It is working! Thank you very much for your help.
I just have another problem with the interactive section, when I tried to run viewer = img.interactive(adata) I am getting this error.

  File "C:\Users\mertd\anaconda3\lib\site-packages\squidpy\pl\_interactive\interactive.py", line 40, in __init__
    raise ImportError(f"Unable to import the interactive viewer. Reason `{_error}`.")

ImportError: Unable to import the interactive viewer. Reason `No module named 'napari'`.

**Comment by michalk8** [comment]
> ImportError: Unable to import the interactive viewer. Reason No module named 'napari'.

We have `napari` only as extra requirement; the versions we need are `"PyQt5>=5.15.0"` and  `"napari>=0.4.14,<0.5"`.
`pip install "PyQt5>=5.15.0" "napari>=0.4.14,<0.5"` or 
`pip install "git+https://github.com/theislab/squidpy@master#egg=squidpy[interactive]"` should fix this.

**Comment by MertDemirdizen** [comment]
`pip install "PyQt5>=5.15.0" 
I am getting "DLL load failed while importing pyrcc" but I think it is not relevant to you but about my system.  I will try to fix it.

Thank you very much for your help.

**Comment by MertDemirdizen** [comment]
Hi,
Reinstalling process did not work but, I solved my problem by creating another environment.
Thank you very much for your quick responses. You helped a lot!
