### ISSUE TITLE
neighborhood enrichment z scores

### ISSUE THREAD

**Issue by vicmuliadi** [theislab/squidpy#501]
Hello,

Thank you for developing this nice tool! I've been using it to run some neighborhood enrichment analysis, and I noticed that the enrichment z score between pairs of the same cluster types is not always the maximum score. Is this possible? And what would be the best way to interpret these results?

Thank you!

**Comment by MxMstrmn** [comment]
Hey @vicmuliadi, 

cool that you find squidpy useful! Do you mind providing a minimal code example that shows what you are doing specifically?

**Comment by vicmuliadi** [comment]
Thanks for answering @MxMstrmn! Here's a bit of the code I'm using (I'm trying to calculate the neighborhood enrichment scores between different genes in an _in situ_ sequencing dataset):

`sq.gr.spatial_neighbors(adata, coord_type = "generic", n_neighs = 10, delaunay = False)`
`sq.gr.nhood_enrichment(adata, cluster_key="gene_names")`
`sq.pl.nhood_enrichment(adata, cluster_key="gene_names")`

and here is how the resulting graph looks like: 
![bc8 nhood enrichment](https://user-images.githubusercontent.com/71453742/162448063-eceb0599-b14b-4f80-bdc1-c6e1b16c6926.png)

From my own understanding one would expect the enrichment scores between pairs of the same genes (i.e. the diagonal line through the matrix) to be the maximum possible score, but this is not always the case here.
Could it be due to the input data itself (e.g. differences in signal density of the genes)?

**Comment by MxMstrmn** [comment]
Hi @vicmuliadi, 
thanks for providing this example, that already helped a lot understanding your problem. Please have a look at this [part](https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_visium_hne.html#neighborhood-enrichment) of the squidpy tutorials. The enrichment scores tell you something about the _spatial co-occurence of clusters_ and therefore clusters of the same type do not have to occur together, but can be distributed across the whole tissue.

**Comment by vicmuliadi** [comment]
Ah that makes sense, I understand now. Thank you!
