### ISSUE TITLE
weired squidpy plot

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/squidpy#505]
Hi,
Each time I run sq.pl function and save the plot, such as sq.pl.ripley(adata, cluster_key="leiden", mode="L", save="c.pdf"), a wired file like "<property object at 0x7ffbce70a8b0>/" is generated in the directory. If I don't save the plot (without  save="c.pdf"), the file are not generated.

**Comment by michalk8** [comment]
Hi @wangjiawen2013 , we're using `scanpy.settings.figdir`, can you before plotting check it as:
```python
from scanpy import settings
print(settings.figdir)
```
