### ISSUE TITLE
dask array to numpy array

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/squidpy#517]
Hi,
I am learning to import spatial data in AnnData and Squidpy: 
https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_read_spatial.html

Now I have an image object, the layers are stored in dsarray format. I want to extract the dask array to numpy array, and store the image (in numpy array format) in an anndata object. Then how to extract the image data, or can I stored the image object to anndata directly without format transform ?
Because only images in numpy array can be saved according to the tutorial, so I must convert dsarray to numpy array first:

```python
rng = default_rng(42)
counts = rng.integers(0, 15, size=(10, 100))  # feature matrix
coordinates = rng.uniform(0, 10, size=(10, 2))  # spatial coordinates
image = rng.uniform(0, 1, size=(10, 10, 3))  # image
spatial_key = "spatial"
library_id = "tissue42"
adata.uns[spatial_key] = {library_id: {}}
adata.uns[spatial_key][library_id]["images"] = {}
adata.uns[spatial_key][library_id]["images"] = {"hires": image}
adata.uns[spatial_key][library_id]["scalefactors"] = {"tissue_hires_scalef": 1, "spot_diameter_fullres": 0.5}
```

**Comment by michalk8** [comment]
Hi @wangjiawen2013 ,

> Then how to extract the image data, or can I stored the image object to anndata directly without format transform ?

Are you asking whether `dask.arrays` can be stored in `AnnData` directly in `.uns`? Afaik it's possible, but, e.g., saving won't work (yet) - really depends on what you plan on doing downstream.
So I'd recommend saving it as an array, see below example:
```python
import squidpy as sq
import dask.array as da

adata = sq.datasets.visium_fluo_adata_crop()
img = sq.datasets.visium_fluo_image_crop()

arr = img['image'].data
assert isinstance(arr, da.Array)

adata.uns['spatial']['V1_Adult_Mouse_Brain_Coronal_Section_2']['images']['darr'] = arr.compute()

adata.write("foo.h5ad")  # not calling `.compute()` would make this step fail 
```

**Comment by wangjiawen2013** [comment]
> hi @wangjiawen2013 does that answer your question? I'm not sure how much support for dask arrays there is in anndata yet.

Yes, thank you!
