### ISSUE TITLE
Exporting selected points from a Napari window is broken

### ISSUE THREAD

**Issue by ilia-kats** [theislab/squidpy#530]
Steps to reproduce:
Visualize some Visium data set using something like
```
image = sq.im.ImageContainer(adata.uns["spatial"]["spaceranger100_count_30458_ST8059048_mm10-3_0_0_premrna"]["images"]["hires"], scale=adata.uns["spatial"]["spaceranger100_count_30458_ST8059048_mm10-3_0_0_premrna"]["scalefactors"]["tissue_hires_scalef"], library_id="spaceranger100_count_30458_ST8059048_mm10-3_0_0_premrna")
viewer = image.interactive(adata)
```

Create a new shape layer, create a polygon selecting some points and press `Shift+E`. A new column appears in the `Observations` dock, but looking at `adata.obs` in the Python console does not show the new column.

This is because `ImageController._save_shapes` [modifies `self.model.adata`](https://github.com/theislab/squidpy/blob/master/squidpy/pl/_interactive/_controller.py#L265). However, `ImageModel` stores a copy of the original AnnData object instead of a reference: [It calls `ImageContainer._subset`](https://github.com/theislab/squidpy/blob/master/squidpy/pl/_interactive/_model.py#L44), [which then creates a copy](https://github.com/theislab/squidpy/blob/master/squidpy/im/_container.py#L1293).

**Comment by michalk8** [comment]
The copy is currently necessary as it modifies the coordinates inplace (when `scale!=1` or when the container is a crop).
Currently, I don't see an immediate solution to this; some possibilities are:
- using a context manager
- creating a new, key for spatial coordinates, e.g. `'_spatial'`

Any opinion @giovp ?
In any case, `Interactive` object has the `.adata` attribute that should have the corresponding column.

**Comment by giovp** [comment]
> Create a new shape layer, create a polygon selecting some points and press Shift+E. A new column appears in the Observations dock, but looking at adata.obs in the Python console does not show the new column.

Indeed, you'd have to check in the `viewer.adata` object, which is needed for the cases @michalk8 has described above. @michalk8 how would you envision a context manager in this context? @ilia-kats what do you think could be a solution?

Personally I don't think it's a big problem as users could still copy over the annotation to the old anndata. Maybe should be better documented?

**Comment by ilia-kats** [comment]
Yeah, as long as you update the Napari tutorial, it should be fine. It's still not very intuitive though, you're passing an AnnData object to `interactive`, so from the outside it's not immediately clear why the shapes are not stored directly in that object. Unfortunately I'm not familiar enogh with SquidPy internals to suggest a solution for this at the moment.
