### ISSUE TITLE
problem with installation pyqt5 version

### ISSUE THREAD

**Issue by sophieRAIBAUD** [theislab/squidpy#538]
...
dear all,
first thanks for this tool which will be very helpfull!
I am strugling with the installation 
when I use pip install 'squidpy[interactive]'
I got these errors:
ERROR: spyder 4.1.4 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.15.6 which is incompatible.
ERROR: omnipath 1.0.5 has requirement typing-extensions>=3.7.4.3, but you'll have typing-extensions 3.7.4.2 which is incompatible.
ERROR: pydantic 1.9.0 has requirement typing-extensions>=3.7.4.3, but you'll have typing-extensions 3.7.4.2 which is incompatible.
ERROR: superqt 0.3.1 has requirement typing-extensions>=3.10.0.0, but you'll have typing-extensions 3.7.4.2 which is incompatible.
and
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

I use Python 3.8.3

Many thanks !
Sophie

**Comment by sophieRAIBAUD** [comment]
I think I found the solution :
pip install llvmlite --ignore-installed

**Comment by nadavyayon** [comment]
HI, for me going back to `squidpy==1.1.2`  vesrion solved all these issues
