### ISSUE TITLE
alpha parameter in sq.pl.spatial_scatter

### ISSUE THREAD

**Issue by jnmark** [theislab/squidpy#540]
I am trying to use the 'alpha' parameter in spatial_scatter, but regardless of what value I try between 0 and 1, the spot opacity doesn't seem to change. On the other hand 'img_alpha' works perfectly Am I doing something wrong?

`sq.pl.spatial_scatter(adata, alpha = 0.1, color='texturefeatures_cluster_05')`

**Comment by michalk8** [comment]
Hi @jnmark ,

I've tried running:
```python
import squidpy as sq

adata = sq.datasets.visium_hne_adata()
sq.pl.spatial_scatter(adata, color="Sox8", alpha=0.5)
```
and it works. However, running this for categorical observation, it has no effect. Is `texturefeatures_cluster_05` categorical in your case?

**Comment by jnmark** [comment]
Yes, it is categorical. These are the texture based features extracted from
Squidpy. I would like to make them opaque or fully transparent with just
the spot outline so I can see the H&E and understand the underlying
texture.

**Comment by michalk8** [comment]
Should be fixed now.

**Comment by jnmark** [comment]
Thanks so much! I installed the latest git version to test this, however, now I get another error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-5fe2ac371d8c> in <module>
      3 sc.settings.set_figure_params(figsize = [10,10])
----> 5 sq.pl.spatial_scatter(adata, alpha = 0.1, color='textfeatures_cluster_05')

AttributeError: module 'squidpy' has no attribute 'pl'

**Comment by cathalgking** [comment]
@jnmark Did you manage to get transparent spots for this method? I would like to plot a spatial image with gene counts but have transparent spots for spots that have zero counts. Do you know if I can do this with squidpy?
<img width="516" alt="Screen Shot 2023-08-02 at 7 48 59 pm" src="https://github.com/scverse/squidpy/assets/32261323/de37aef5-bd8f-41b5-9a49-40403de7ba3e">
